# Requests to test our API routes easily (without a frontend)

# In order to use this file => install VsCode extension "REST Client" from "Huachao Mao"
# Start your backend
# You should see a link "Send Request" popping up above each request

# Testing routes using a requests file like this is recommend to test
# the functionality of the backend FIRST, before connecting a frontend and debugging issues 
# with the backend from the frontend, which is way more difficult 

@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYmJvcyIsImlhdCI6MTcxOTE2NjgyOCwiZXhwIjoxNzE5MTY4NjI4fQ.6Zlf9Lyt3jD6uWXc_AQcUEX2yepcG9kE3qzPiwcHExg

### Test home route of backend
GET {{API_URL}}

### GET list of all users (to check if signups worked)
GET {{API_URL}}/users

### SIGNUP Route
POST {{API_URL}}/auth/signup
Content-Type: application/json

{
  "username": "robbos",
  "email": "robbos@rob.com",
  "password": "r123"
}

### Login route
POST {{API_URL}}/auth/login
Content-Type: application/json

{
  "email": "robbos@rob.com",
  "password": "r123"
}


### Protected route to check if token is valid
GET {{API_URL}}/me
Authorization: {{TOKEN}}

