# Requests to test our API routes easily (without a frontend)

# In order to use this file => install VsCode extension "REST Client" from "Huachao Mao"
# Start your backend
# You should see a link "Send Request" popping up above each request

# Testing routes using a requests file like this is recommend to test
# the functionality of the backend FIRST, before connecting a frontend and debugging issues 
# with the backend from the frontend, which is way more difficult 

@API_URL = http://localhost:5000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsInVzZXJuYW1lIjoicm9iYm9zIiwiaWF0IjoxNzE5MjUzODYwLCJleHAiOjE3MTkyNTU2NjB9.AJlTUB1D-E89AwmZbbKtWc-19cmmZu0FG8ZXn2wrwKo

### Test home route of backend
GET {{API_URL}}

### Login route
POST {{API_URL}}/auth/login
Content-Type: application/json

{
  "email": "robbos@rob.com",
  "password": "r123"
}

### SIGNUP Route
POST {{API_URL}}/auth/signup
Content-Type: application/json

{
  "username": "robbos",
  "email": "robbos@rob.com",
  "password": "r123"
}



### Protected route to check if token is valid
GET {{API_URL}}/users/me
Authorization: {{TOKEN}}

### GET list of all users (to check if signups worked)
GET {{API_URL}}/users
Authorization: {{TOKEN}}

### Delete user
DELETE  {{API_URL}}/users/4
Authorization: {{TOKEN}}

### Update user
PATCH {{API_URL}}/users/3
Content-Type: application/json
Authorization: {{TOKEN}}

{
  "username": "Bob"
}

### Get single user
GET {{API_URL}}/users/1
Authorization: {{TOKEN}}

### Get users posts
GET {{API_URL}}/users/1/posts
Authorization: {{TOKEN}}

### Get post with author
GET {{API_URL}}/posts/1
Authorization: {{TOKEN}}


### Create related post
POST {{API_URL}}/posts
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "title": "Newww Post 2.0"
}